#!/usr/bin/env ruby
require 'rubygems'
$:.unshift(File.expand_path("../../lib", __FILE__))
require "bundler/setup"
require 'logger'
require 'rdf/normalize'
require_relative "../spec/spec_helper"
require_relative "../spec/suite_helper"
require 'getoptlong'

ASSERTOR = "https://greggkellogg.net/foaf#me"
RUN_TIME = Time.now

def earl_preamble(options)
  options[:output].write File.read(File.expand_path("../../etc/doap.ttl", __FILE__))
  options[:output].puts %(
<https://rubygems.org/gems/rdf-normalize> doap:release [
  doap:name "rdf-normalize-#{RDF::Normalize::VERSION}";
  doap:revision "#{RDF::Normalize::VERSION}";
  doap:created "#{File.mtime(File.expand_path('../../VERSION', __FILE__)).strftime('%Y-%m-%d')}"^^xsd:date;
] .
<> foaf:primaryTopic <https://rubygems.org/gems/rdf-normalize> ;
  dc:issued "#{RUN_TIME.xmlschema}"^^xsd:dateTime ;
  foaf:maker <#{ASSERTOR}> .

<#{ASSERTOR}> a foaf:Person, earl:Assertor;
  foaf:name "Gregg Kellogg";
  foaf:title "Implementor";
  foaf:homepage <https://greggkellogg.net/> .
)
end

def run_tc(tc, **options)
  $stderr.write "run #{tc.id}"

  if options[:verbose]
    puts "\nTestCase: #{tc.inspect}"
    puts "\nInput:\n" + tc.input 
    puts "\nExpected:\n" + tc.expected
  end

  output, result = nil, nil

  begin
    puts "open #{tc.action}" if options[:verbose]
    options = {base_uri:  tc.base}.merge(options)
    options[:hash_algorithm] = options.delete(:algorithm).to_sym if options[:algorithm]

    dataset = RDF::Repository.load(tc.action, format: :nquads)
    result = if tc.type == 'rdfc:RDFC10MapTest'
      input_map = RDF::Normalize::RDFC10.new(dataset, **options).to_hash
      result_map = JSON.load(tc.expected)
      output = input_map.to_json(JSON::LD::JSON_STATE)
      input_map == result_map ? "passed" : "failed"
    elsif tc.type == 'rdfc:RDFC10NegativeEvalTest'
      begin
        RDF::Normalize::RDFC10.new(dataset, **options).to_hash
        "failed" # Should raise exception
      rescue ::RDF::Normalize::MaxCallsExceeded
        "passed"
      end
    else
      output = dataset.dump(:normalize, **tc.writer_options.merge(options))
      output == tc.expected ? "passed" : "failed"
    end

    options[:results][result] ||= 0
    options[:results][result] += 1
  rescue Interrupt
    $stderr.puts " (interrupt)"
    exit 1
  rescue StandardError => e
    $stderr.puts " #{"exception:" unless options[:quiet]}: #{e}"
    if options[:quiet]
      options[:results]['failed'] ||= 0
      options[:results]['failed'] += 1
    else
      raise
    end
  end

  options[:output].puts("\nOutput:\n" + output) if options[:verbose]

  if options[:earl]
    options[:output].puts %{
[ a earl:Assertion;
  earl:assertedBy <#{ASSERTOR}>;
  earl:subject <https://rubygems.org/gems/rdf-normalize>;
  earl:test <#{Fixtures::SuiteTest::BASE + "manifest" + tc.id}>;
  earl:result [
    a earl:TestResult;
    earl:outcome earl:#{result};
    dc:date "#{RUN_TIME.xmlschema}"^^xsd:dateTime];
  earl:mode earl:automatic ] .
}
  end

  puts "#{" test result:" unless options[:quiet]} #{result}"
end

logger = Logger.new(STDERR)
logger.level = Logger::WARN
logger.formatter = lambda {|severity, datetime, progname, msg| "#{severity}: #{msg}\n"}

options = {
  output:  STDOUT,
  results: {},
  logger: logger
}

OPT_ARGS = [
  ["--help", "-?", GetoptLong::NO_ARGUMENT,         "This message"],
  ["--debug", GetoptLong::NO_ARGUMENT,              "Display detailed debug output"],
  ["--earl", GetoptLong::NO_ARGUMENT,               "Generate EARL report"],
  ["--max-calls", GetoptLong::REQUIRED_ARGUMENT,    "Factor for maximum allowed calls to Hash N-Degree Quads"],
  ["--output", "-o", GetoptLong::REQUIRED_ARGUMENT, "Output to specified file"],
  ["--quiet", "-q", GetoptLong::NO_ARGUMENT,        "Minimal output"],
  ["--validate", GetoptLong::NO_ARGUMENT,           "Validate input"],
  ["--verbose", "-v", GetoptLong::NO_ARGUMENT,      "Verbose processing"],
  ["--yaml", GetoptLong::NO_ARGUMENT,               "Debug output as YAML"],
]

def help(options)
  STDERR.puts %{Usage: #{$0} [options] file ...}
  width = OPT_ARGS.map do |o|
    l = o.first.length
    l += o[1].length + 2 if o[1].is_a?(String)
    l
  end.max
  OPT_ARGS.each do |o|
    s = "  %-*s  " % [width, (o[1].is_a?(String) ? "#{o[0,2].join(', ')}" : o[0])]
    s += o.last
    STDERR.puts s
  end
  exit(0)
end

opts = GetoptLong.new(*OPT_ARGS.map {|o| o[0..-2]})

opts.each do |opt, arg|
  case opt
  when '--help'             then help(options)
  when '--debug'            then logger.level = Logger::DEBUG
  when '--earl'
    options[:quiet] = options[:earl] = true
    logger.level = Logger::FATAL
  when '--max-calls'        then options[:max_calls] = arg.to_i
  when '--output'           then options[:output] = File.open(arg, "w")
  when '--quiet'
    options[:quiet] = true
    logger.level = Logger::FATAL
  when '--validate'         then options[:validate] = true
  when '--verbose'          then options[:verbose] = true
  when '--yaml'
    logger.level = Logger::DEBUG
    logger.formatter = lambda {|severity, datetime, progname, msg| "%s\n" % msg}
  end
end

earl_preamble(options) if options[:earl]

manifest = Fixtures::SuiteTest::BASE + "manifest.jsonld"

Fixtures::SuiteTest::Manifest.open(manifest, manifest[0..-8]) do |m|
  m.entries.each do |tc|
    next unless ARGV.empty? || ARGV.any? {|n| tc.id.match(/#{n}/)}
    run_tc(tc, **options)
  end
end

options[:results].each {|k, v| puts "#{k}: #{v}"}
